// ============================================================
//  VERBOS — compartilhado entre o app de estudo e o jogo (Kotodama Quest).
//  type: godan | ichidan | irregular. Adicione verbos novos aqui.
// ============================================================
window.VERBS_DATA = [
  { jp:'食べる', kana:'たべる', romaji:'taberu', meaning:'comer', type:'ichidan' },
  { jp:'見る', kana:'みる', romaji:'miru', meaning:'ver', type:'ichidan' },
  { jp:'寝る', kana:'ねる', romaji:'neru', meaning:'dormir', type:'ichidan' },
  { jp:'起きる', kana:'おきる', romaji:'okiru', meaning:'acordar', type:'ichidan' },
  { jp:'飲む', kana:'のむ', romaji:'nomu', meaning:'beber', type:'godan' },
  { jp:'読む', kana:'よむ', romaji:'yomu', meaning:'ler', type:'godan' },
  { jp:'書く', kana:'かく', romaji:'kaku', meaning:'escrever', type:'godan' },
  { jp:'話す', kana:'はなす', romaji:'hanasu', meaning:'falar', type:'godan' },
  { jp:'待つ', kana:'まつ', romaji:'matsu', meaning:'esperar', type:'godan' },
  { jp:'買う', kana:'かう', romaji:'kau', meaning:'comprar', type:'godan' },
  { jp:'泳ぐ', kana:'およぐ', romaji:'oyogu', meaning:'nadar', type:'godan' },
  { jp:'遊ぶ', kana:'あそぶ', romaji:'asobu', meaning:'brincar', type:'godan' },
  { jp:'死ぬ', kana:'しぬ', romaji:'shinu', meaning:'morrer', type:'godan' },
  { jp:'帰る', kana:'かえる', romaji:'kaeru', meaning:'voltar', type:'godan' },
  { jp:'行く', kana:'いく', romaji:'iku', meaning:'ir', type:'irregular' },
  { jp:'する', kana:'する', romaji:'suru', meaning:'fazer', type:'irregular' },
  { jp:'来る', kana:'くる', romaji:'kuru', meaning:'vir', type:'irregular' },
  { jp:'降る', kana:'ふる', romaji:'furu', meaning:'cair / chover', type:'godan' },
  { jp:'住む', kana:'すむ', romaji:'sumu', meaning:'morar', type:'godan' },
  { jp:'働く', kana:'はたらく', romaji:'hataraku', meaning:'trabalhar', type:'godan' },
  { jp:'知る', kana:'しる', romaji:'shiru', meaning:'saber / conhecer', type:'godan' },
  { jp:'作る', kana:'つくる', romaji:'tsukuru', meaning:'fazer / criar', type:'godan' },
  { jp:'持つ', kana:'もつ', romaji:'motsu', meaning:'ter / segurar', type:'godan' },
  { jp:'飛ぶ', kana:'とぶ', romaji:'tobu', meaning:'voar / pular', type:'godan' },
  { jp:'咲く', kana:'さく', romaji:'saku', meaning:'florescer', type:'godan' },
  { jp:'走る', kana:'はしる', romaji:'hashiru', meaning:'correr', type:'godan' },
  { jp:'結婚する', kana:'けっこんする', romaji:'kekkonsuru', meaning:'casar(-se)', type:'irregular' },
  { jp:'手伝う', kana:'てつだう', romaji:'tetsudau', meaning:'ajudar', type:'godan' },
  { jp:'つける', kana:'つける', romaji:'tsukeru', meaning:'ligar / acender', type:'ichidan' },
  { jp:'見せる', kana:'みせる', romaji:'miseru', meaning:'mostrar', type:'ichidan' },
  { jp:'座る', kana:'すわる', romaji:'suwaru', meaning:'sentar(-se)', type:'godan' },
  { jp:'曲がる', kana:'まがる', romaji:'magaru', meaning:'virar / dobrar', type:'godan' },
  { jp:'置く', kana:'おく', romaji:'oku', meaning:'colocar / pôr', type:'godan' },
  { jp:'使う', kana:'つかう', romaji:'tsukau', meaning:'usar', type:'godan' },
  { jp:'借りる', kana:'かりる', romaji:'kariru', meaning:'pegar emprestado', type:'ichidan' },
  { jp:'もらう', kana:'もらう', romaji:'morau', meaning:'receber / ganhar', type:'godan' },
  { jp:'サインする', kana:'サインする', romaji:'sainsuru', meaning:'assinar', type:'irregular' },
  { jp:'吸う', kana:'すう', romaji:'suu', meaning:'fumar / inalar', type:'godan' },
  { jp:'押す', kana:'おす', romaji:'osu', meaning:'empurrar / apertar', type:'godan' },
  { jp:'歌う', kana:'うたう', romaji:'utau', meaning:'cantar', type:'godan' },
  { jp:'消す', kana:'けす', romaji:'kesu', meaning:'apagar / desligar', type:'godan' },
  { jp:'呼ぶ', kana:'よぶ', romaji:'yobu', meaning:'chamar', type:'godan' },
  { jp:'教える', kana:'おしえる', romaji:'oshieru', meaning:'ensinar', type:'ichidan' },
  { jp:'始める', kana:'はじめる', romaji:'hajimeru', meaning:'começar (algo)', type:'ichidan' },
  { jp:'閉める', kana:'しめる', romaji:'shimeru', meaning:'fechar', type:'ichidan' },
  { jp:'開ける', kana:'あける', romaji:'akeru', meaning:'abrir', type:'ichidan' },
  { jp:'あげる', kana:'あげる', romaji:'ageru', meaning:'dar', type:'ichidan' },
  { jp:'持ってくる', kana:'もってくる', romaji:'mottekuru', meaning:'trazer', type:'irregular' },
  { jp:'ある', kana:'ある', romaji:'aru', meaning:'haver (coisas)', type:'godan' },
  { jp:'入る', kana:'はいる', romaji:'hairu', meaning:'entrar', type:'godan' },
  { jp:'くれる', kana:'くれる', romaji:'kureru', meaning:'dar (a mim/à minha família)', type:'ichidan' },
  { jp:'直す', kana:'なおす', romaji:'naosu', meaning:'consertar / corrigir', type:'godan' },
  { jp:'迎える', kana:'むかえる', romaji:'mukaeru', meaning:'ir buscar / receber (alguém)', type:'ichidan' },
  { jp:'修理する', kana:'しゅうりする', romaji:'shuurisuru', meaning:'consertar (reparar)', type:'irregular' },
  { jp:'連れて行く', kana:'つれていく', romaji:'tsureteiku', meaning:'levar (uma pessoa)', type:'irregular' }
];
