// ============================================================
//  BARALHOS DE VOCABULÁRIO — Básico 2 (ICBJ)
//  Importados automaticamente pelo app (sem apagar seu progresso).
//  Cada deck tem um id estável: se já existir, não duplica.
//  Para adicionar mais semanas, é só acrescentar novos decks aqui.
//  Campos por card: jp (kana), mean (PT), ex (frase), exTr (tradução).
//  O romaji é gerado automaticamente pelo app.
// ============================================================
window.VOCAB_DECKS = [
  { id:'b2-verbos', name:'Básico 2 — Verbos (ます)', cards:[
    { jp:'あいます', mean:'encontrar (alguém)', ex:'ともだちに あいます。', exTr:'Encontro um amigo.' },
    { jp:'あそびます', mean:'brincar, divertir-se', ex:'こうえんで あそびます。', exTr:'Brinco no parque.' },
    { jp:'あびます', mean:'tomar (ducha)', ex:'シャワーを あびます。', exTr:'Tomo uma ducha.' },
    { jp:'あらいます', mean:'lavar', ex:'てを あらいます。', exTr:'Lavo as mãos.' },
    { jp:'あります', mean:'haver, ter (objetos)', ex:'つくえの うえに ほんが あります。', exTr:'Há um livro sobre a mesa.' },
    { jp:'います', mean:'haver, estar (seres vivos)', ex:'へやに ねこが います。', exTr:'Há um gato no quarto.' },
    { jp:'いきます', mean:'ir', ex:'がっこうへ いきます。', exTr:'Vou para a escola.' },
    { jp:'きます', mean:'vir', ex:'ともだちが きます。', exTr:'Um amigo vem.' },
    { jp:'かえります', mean:'voltar (para casa)', ex:'うちへ かえります。', exTr:'Volto para casa.' },
    { jp:'かいます', mean:'comprar', ex:'パンを かいます。', exTr:'Compro pão.' },
    { jp:'かいものします', mean:'fazer compras', ex:'スーパーで かいものします。', exTr:'Faço compras no mercado.' },
    { jp:'かけます', mean:'telefonar', ex:'でんわを かけます。', exTr:'Faço uma ligação.' },
    { jp:'べんきょうします', mean:'estudar', ex:'にほんごを べんきょうします。', exTr:'Estudo japonês.' },
    { jp:'でます', mean:'sair', ex:'うちを でます。', exTr:'Saio de casa.' },
    { jp:'はいります', mean:'entrar', ex:'へやに はいります。', exTr:'Entro no quarto.' },
    { jp:'はじまります', mean:'começar', ex:'クラスが はじまります。', exTr:'A aula começa.' },
    { jp:'はたらきます', mean:'trabalhar', ex:'かいしゃで はたらきます。', exTr:'Trabalho na empresa.' },
    { jp:'みがきます', mean:'escovar', ex:'はを みがきます。', exTr:'Escovo os dentes.' },
    { jp:'みます', mean:'ver, assistir', ex:'テレビを みます。', exTr:'Vejo TV.' },
    { jp:'ねます', mean:'dormir', ex:'はやく ねます。', exTr:'Durmo cedo.' },
    { jp:'のみます', mean:'beber', ex:'みずを のみます。', exTr:'Bebo água.' },
    { jp:'のります', mean:'embarcar, pegar (transporte)', ex:'でんしゃに のります。', exTr:'Pego o trem.' },
    { jp:'おきます', mean:'acordar, levantar', ex:'あさ ６じに おきます。', exTr:'Acordo às 6 da manhã.' },
    { jp:'おくります', mean:'enviar', ex:'メールを おくります。', exTr:'Envio um e-mail.' },
    { jp:'おります', mean:'descer, desembarcar', ex:'バスを おります。', exTr:'Desço do ônibus.' },
    { jp:'おわります', mean:'terminar, acabar', ex:'しごとが おわります。', exTr:'O trabalho termina.' },
    { jp:'さんぽをします', mean:'passear, caminhar', ex:'いぬと さんぽを します。', exTr:'Passeio com o cachorro.' },
    { jp:'せんたくします', mean:'lavar roupa', ex:'にちようびに せんたくします。', exTr:'Lavo roupa no domingo.' },
    { jp:'そうじします', mean:'faxinar, limpar', ex:'へやを そうじします。', exTr:'Faço faxina no quarto.' },
    { jp:'たべます', mean:'comer', ex:'ごはんを たべます。', exTr:'Como (arroz/comida).' },
    { jp:'つかいます', mean:'usar', ex:'パソコンを つかいます。', exTr:'Uso o computador.' },
    { jp:'とまります', mean:'hospedar-se', ex:'ホテルに とまります。', exTr:'Me hospedo no hotel.' },
    { jp:'まちます', mean:'esperar', ex:'ともだちを まちます。', exTr:'Espero um amigo.' },
    { jp:'わかります', mean:'entender', ex:'にほんごが わかります。', exTr:'Entendo japonês.' },
    { jp:'わたります', mean:'atravessar', ex:'みちを わたります。', exTr:'Atravesso a rua.' },
    { jp:'よみます', mean:'ler', ex:'ほんを よみます。', exTr:'Leio um livro.' },
    { jp:'しにます', mean:'morrer', ex:'はなが しにます。', exTr:'A flor morre.' },
    { jp:'テニスをします', mean:'jogar tênis', ex:'ともだちと テニスを します。', exTr:'Jogo tênis com um amigo.' }
  ]},
  { id:'b2-adj-i', name:'Básico 2 — Adjetivos い', cards:[
    { jp:'あかい', mean:'vermelho', ex:'あかい りんごです。', exTr:'É uma maçã vermelha.' },
    { jp:'あかるい', mean:'claro, alegre', ex:'あかるい へやです。', exTr:'É um quarto claro.' },
    { jp:'あつい', mean:'quente', ex:'きょうは あついです。', exTr:'Hoje está quente.' },
    { jp:'あまい', mean:'doce', ex:'この ケーキは あまいです。', exTr:'Este bolo é doce.' },
    { jp:'はやい', mean:'rápido', ex:'しんかんせんは はやいです。', exTr:'O shinkansen é rápido.' },
    { jp:'ほそい', mean:'fino', ex:'ほそい ペンです。', exTr:'É uma caneta fina.' },
    { jp:'かるい', mean:'leve', ex:'この かばんは かるいです。', exTr:'Esta bolsa é leve.' },
    { jp:'かわいい', mean:'fofo, gracioso', ex:'かわいい いぬですね。', exTr:'Que cachorro fofo!' },
    { jp:'ながい', mean:'longo, comprido', ex:'ながい かわです。', exTr:'É um rio longo.' },
    { jp:'まずい', mean:'ruim de gosto', ex:'この りょうりは まずいです。', exTr:'Esta comida é ruim.' },
    { jp:'めずらしい', mean:'raro', ex:'めずらしい とりです。', exTr:'É um pássaro raro.' },
    { jp:'おいしい', mean:'gostoso', ex:'この すしは おいしいです。', exTr:'Este sushi é gostoso.' },
    { jp:'おおきい', mean:'grande', ex:'おおきい いえです。', exTr:'É uma casa grande.' },
    { jp:'おもしろい', mean:'interessante, divertido', ex:'この ほんは おもしろいです。', exTr:'Este livro é interessante.' },
    { jp:'さむい', mean:'frio', ex:'ふゆは さむいです。', exTr:'O inverno é frio.' },
    { jp:'せまい', mean:'estreito, apertado', ex:'せまい へやです。', exTr:'É um quarto apertado.' },
    { jp:'たかい', mean:'alto, caro', ex:'この とけいは たかいです。', exTr:'Este relógio é caro.' },
    { jp:'うるさい', mean:'barulhento', ex:'この まちは うるさいです。', exTr:'Esta cidade é barulhenta.' },
    { jp:'わかい', mean:'jovem', ex:'わかい せんせいです。', exTr:'É um professor jovem.' },
    { jp:'やさしい', mean:'gentil, fácil', ex:'やさしい ひとです。', exTr:'É uma pessoa gentil.' },
    { jp:'やすい', mean:'barato', ex:'この みせは やすいです。', exTr:'Esta loja é barata.' }
  ]},
  { id:'b2-adj-na', name:'Básico 2 — Adjetivos な', cards:[
    { jp:'あんぜん', mean:'seguro', ex:'ここは あんぜんです。', exTr:'Aqui é seguro.' },
    { jp:'ハンサム', mean:'bonito (pessoa)', ex:'ハンサムな ひとです。', exTr:'É uma pessoa bonita.' },
    { jp:'じょうぶ', mean:'resistente', ex:'じょうぶな くつです。', exTr:'São sapatos resistentes.' },
    { jp:'きれい', mean:'bonito, limpo', ex:'きれいな はなです。', exTr:'É uma flor bonita.' },
    { jp:'まじめ', mean:'sério, aplicado', ex:'まじめな がくせいです。', exTr:'É um aluno aplicado.' },
    { jp:'にぎやか', mean:'movimentado, animado', ex:'にぎやかな まちです。', exTr:'É uma cidade movimentada.' },
    { jp:'たいへん', mean:'trabalhoso, difícil', ex:'たいへんな しごとです。', exTr:'É um trabalho difícil.' },
    { jp:'しずか', mean:'calmo, tranquilo', ex:'しずかな こうえんです。', exTr:'É um parque tranquilo.' },
    { jp:'しんせつ', mean:'gentil, atencioso', ex:'しんせつな てんいんです。', exTr:'É um atendente gentil.' },
    { jp:'ゆうめい', mean:'famoso', ex:'ゆうめいな レストランです。', exTr:'É um restaurante famoso.' }
  ]},
  { id:'b2-tempo', name:'Básico 2 — Tempo e frequência', cards:[
    { jp:'あさって', mean:'depois de amanhã', ex:'あさって きます。', exTr:'Venho depois de amanhã.' },
    { jp:'あした', mean:'amanhã', ex:'あした がっこうへ いきます。', exTr:'Amanhã vou à escola.' },
    { jp:'きのう', mean:'ontem', ex:'きのう えいがを みました。', exTr:'Ontem vi um filme.' },
    { jp:'おととい', mean:'anteontem', ex:'おととい かえりました。', exTr:'Voltei anteontem.' },
    { jp:'けさ', mean:'esta manhã', ex:'けさ ６じに おきました。', exTr:'Acordei às 6 hoje de manhã.' },
    { jp:'こんばん', mean:'esta noite', ex:'こんばん べんきょうします。', exTr:'Hoje à noite vou estudar.' },
    { jp:'ゆうべ', mean:'ontem à noite', ex:'ゆうべ よく ねました。', exTr:'Dormi bem ontem à noite.' },
    { jp:'ゆうがた', mean:'fim de tarde', ex:'ゆうがたに かえります。', exTr:'Volto no fim da tarde.' },
    { jp:'ことし', mean:'este ano', ex:'ことし にほんへ いきます。', exTr:'Este ano vou ao Japão.' },
    { jp:'こんしゅう', mean:'esta semana', ex:'こんしゅうは いそがしいです。', exTr:'Esta semana estou ocupado.' },
    { jp:'せんしゅう', mean:'semana passada', ex:'せんしゅう やすみました。', exTr:'Descansei semana passada.' },
    { jp:'せんげつ', mean:'mês passado', ex:'せんげつ きました。', exTr:'Vim mês passado.' },
    { jp:'らいげつ', mean:'mês que vem', ex:'らいげつ りょこうします。', exTr:'Mês que vem viajo.' },
    { jp:'らいしゅう', mean:'semana que vem', ex:'らいしゅう あいましょう。', exTr:'Vamos nos encontrar semana que vem.' },
    { jp:'らいねん', mean:'ano que vem', ex:'らいねん にほんへ いきます。', exTr:'Ano que vem vou ao Japão.' },
    { jp:'まいあさ', mean:'toda manhã', ex:'まいあさ コーヒーを のみます。', exTr:'Toda manhã bebo café.' },
    { jp:'まいにち', mean:'todo dia', ex:'まいにち べんきょうします。', exTr:'Estudo todo dia.' },
    { jp:'まいばん', mean:'toda noite', ex:'まいばん テレビを みます。', exTr:'Toda noite vejo TV.' },
    { jp:'まいしゅう', mean:'toda semana', ex:'まいしゅう およぎます。', exTr:'Nado toda semana.' },
    { jp:'まいつき', mean:'todo mês', ex:'まいつき ほんを かいます。', exTr:'Todo mês compro um livro.' },
    { jp:'まいとし', mean:'todo ano', ex:'まいとし りょこうします。', exTr:'Todo ano viajo.' },
    { jp:'なつやすみ', mean:'férias de verão', ex:'なつやすみは たのしいです。', exTr:'As férias de verão são divertidas.' },
    { jp:'やすみ', mean:'folga, descanso', ex:'あした やすみです。', exTr:'Amanhã é folga.' },
    { jp:'やすみのひ', mean:'dia de folga', ex:'やすみのひに あそびます。', exTr:'No dia de folga me divirto.' },
    { jp:'いっしゅうかん', mean:'uma semana (duração)', ex:'いっしゅうかん やすみます。', exTr:'Descanso por uma semana.' },
    { jp:'いちにち', mean:'um dia', ex:'いちにち べんきょうしました。', exTr:'Estudei o dia todo.' },
    { jp:'～ごろ', mean:'por volta de (hora)', ex:'７じごろ おきます。', exTr:'Acordo por volta das 7.' },
    { jp:'つぎ', mean:'próximo, seguinte', ex:'つぎの えきで おります。', exTr:'Desço na próxima estação.' },
    { jp:'もう', mean:'já', ex:'もう たべました。', exTr:'Já comi.' },
    { jp:'まだ', mean:'ainda', ex:'まだ じかんが あります。', exTr:'Ainda há tempo.' }
  ]},
  { id:'b2-comida', name:'Básico 2 — Comida e bebida', cards:[
    { jp:'あさごはん', mean:'café da manhã', ex:'あさごはんを たべます。', exTr:'Como café da manhã.' },
    { jp:'ひるごはん', mean:'almoço', ex:'ひるごはんは パンです。', exTr:'O almoço é pão.' },
    { jp:'ばんごはん', mean:'jantar', ex:'ばんごはんを たべます。', exTr:'Como o jantar.' },
    { jp:'ちょうしょく', mean:'café da manhã (formal)', ex:'ホテルの ちょうしょくは おいしいです。', exTr:'O café da manhã do hotel é gostoso.' },
    { jp:'しょくじ', mean:'refeição', ex:'ともだちと しょくじします。', exTr:'Faço uma refeição com um amigo.' },
    { jp:'ビール', mean:'cerveja', ex:'ビールを のみます。', exTr:'Bebo cerveja.' },
    { jp:'ジュース', mean:'suco', ex:'ジュースが すきです。', exTr:'Gosto de suco.' },
    { jp:'おちゃ', mean:'chá', ex:'おちゃを のみましょう。', exTr:'Vamos tomar chá.' },
    { jp:'ミルク', mean:'leite', ex:'まいあさ ミルクを のみます。', exTr:'Toda manhã bebo leite.' },
    { jp:'にほんしゅ', mean:'saquê (japonês)', ex:'にほんしゅを のみます。', exTr:'Bebo saquê.' },
    { jp:'スープ', mean:'sopa', ex:'スープが おいしいです。', exTr:'A sopa está gostosa.' },
    { jp:'ケーキ', mean:'bolo', ex:'ケーキを たべます。', exTr:'Como bolo.' },
    { jp:'トースト', mean:'torrada', ex:'あさ トーストを たべます。', exTr:'De manhã como torrada.' },
    { jp:'くだもの', mean:'frutas', ex:'くだものが すきです。', exTr:'Gosto de frutas.' },
    { jp:'さかな', mean:'peixe', ex:'さかなを たべます。', exTr:'Como peixe.' },
    { jp:'いわし', mean:'sardinha', ex:'いわしは やすいです。', exTr:'A sardinha é barata.' },
    { jp:'オレンジ', mean:'laranja', ex:'オレンジを かいます。', exTr:'Compro laranja.' },
    { jp:'コーヒーカップ', mean:'xícara de café', ex:'コーヒーカップを かいました。', exTr:'Comprei uma xícara de café.' }
  ]},
  { id:'b2-lugares', name:'Básico 2 — Lugares e cidade', cards:[
    { jp:'アパート', mean:'apartamento', ex:'あたらしい アパートです。', exTr:'É um apartamento novo.' },
    { jp:'ぶんぼうぐや', mean:'papelaria', ex:'ぶんぼうぐやで ペンを かいます。', exTr:'Compro caneta na papelaria.' },
    { jp:'どうぶつえん', mean:'zoológico', ex:'どうぶつえんへ いきます。', exTr:'Vou ao zoológico.' },
    { jp:'エレベーター', mean:'elevador', ex:'エレベーターに のります。', exTr:'Pego o elevador.' },
    { jp:'はなや', mean:'floricultura', ex:'はなやで ばらを かいます。', exTr:'Compro rosas na floricultura.' },
    { jp:'いけ', mean:'lago, açude', ex:'こうえんに いけが あります。', exTr:'Há um lago no parque.' },
    { jp:'じむしつ', mean:'escritório', ex:'じむしつで はたらきます。', exTr:'Trabalho no escritório.' },
    { jp:'こうえん', mean:'parque', ex:'こうえんで あそびます。', exTr:'Brinco no parque.' },
    { jp:'こや', mean:'jaula, cabana', ex:'こやに とりが います。', exTr:'Há um pássaro na jaula.' },
    { jp:'まち', mean:'cidade', ex:'にぎやかな まちです。', exTr:'É uma cidade movimentada.' },
    { jp:'みち', mean:'caminho, rua', ex:'この みちは ながいです。', exTr:'Este caminho é longo.' },
    { jp:'おふろ', mean:'banho, banheira', ex:'おふろに はいります。', exTr:'Tomo banho.' },
    { jp:'ろうか', mean:'corredor', ex:'ろうかを あるきます。', exTr:'Ando pelo corredor.' },
    { jp:'レストラン', mean:'restaurante', ex:'レストランで たべます。', exTr:'Como no restaurante.' },
    { jp:'パンや', mean:'padaria', ex:'パンやで パンを かいます。', exTr:'Compro pão na padaria.' },
    { jp:'やっきょく', mean:'farmácia', ex:'やっきょくで くすりを かいます。', exTr:'Compro remédio na farmácia.' },
    { jp:'うりば', mean:'seção de vendas', ex:'３かいの うりばです。', exTr:'É a seção do 3º andar.' },
    { jp:'いりぐち', mean:'entrada', ex:'いりぐちは あそこです。', exTr:'A entrada é ali.' },
    { jp:'いま', mean:'sala de estar', ex:'いまで テレビを みます。', exTr:'Vejo TV na sala.' },
    { jp:'きっさてん', mean:'cafeteria', ex:'きっさてんで コーヒーを のみます。', exTr:'Tomo café na cafeteria.' },
    { jp:'ぎんざ', mean:'Ginza (bairro de Tóquio)', ex:'ぎんざで かいものします。', exTr:'Faço compras em Ginza.' },
    { jp:'さっぽろ', mean:'Sapporo (cidade)', ex:'さっぽろは さむいです。', exTr:'Sapporo é frio.' },
    { jp:'がいこく', mean:'exterior, estrangeiro', ex:'がいこくの えいがを みます。', exTr:'Vejo filmes estrangeiros.' },
    { jp:'ししゃ', mean:'filial', ex:'リオの ししゃで はたらきます。', exTr:'Trabalho na filial do Rio.' },
    { jp:'まわり', mean:'ao redor, em volta', ex:'えきの まわりに みせが あります。', exTr:'Há lojas ao redor da estação.' },
    { jp:'がわ', mean:'lado', ex:'みちの みぎがわです。', exTr:'É do lado direito da rua.' },
    { jp:'まっすぐ', mean:'reto, em frente', ex:'まっすぐ いって ください。', exTr:'Vá em frente, por favor.' }
  ]},
  { id:'b2-pessoas', name:'Básico 2 — Pessoas e animais', cards:[
    { jp:'えいぎょうぶちょう', mean:'diretor comercial', ex:'あの ひとは えいぎょうぶちょうです。', exTr:'Aquela pessoa é o diretor comercial.' },
    { jp:'ガールフレンド', mean:'namorada', ex:'ガールフレンドと あいます。', exTr:'Encontro minha namorada.' },
    { jp:'かしゅ', mean:'cantor(a)', ex:'ゆうめいな かしゅです。', exTr:'É um cantor famoso.' },
    { jp:'おきゃくさん', mean:'cliente, freguês', ex:'おきゃくさんが きました。', exTr:'O cliente chegou.' },
    { jp:'おとこ', mean:'homem', ex:'あの おとこの ひとです。', exTr:'É aquele homem.' },
    { jp:'おんな', mean:'mulher', ex:'あの おんなの ひとです。', exTr:'É aquela mulher.' },
    { jp:'まご', mean:'neto(a)', ex:'まごが ふたり います。', exTr:'Tenho dois netos.' },
    { jp:'しゃちょう', mean:'presidente (de empresa)', ex:'しゃちょうは いそがしいです。', exTr:'O presidente está ocupado.' },
    { jp:'せいねん', mean:'jovem (rapaz)', ex:'げんきな せいねんです。', exTr:'É um jovem cheio de energia.' },
    { jp:'どうぶつ', mean:'animal', ex:'どうぶつが すきです。', exTr:'Gosto de animais.' },
    { jp:'キリン', mean:'girafa', ex:'どうぶつえんに キリンが います。', exTr:'Há uma girafa no zoológico.' },
    { jp:'こいぬ', mean:'cachorrinho', ex:'かわいい こいぬです。', exTr:'É um cachorrinho fofo.' },
    { jp:'さる', mean:'macaco', ex:'やまに さるが います。', exTr:'Há macacos na montanha.' },
    { jp:'とら', mean:'tigre', ex:'どうぶつえんで とらを みました。', exTr:'Vi um tigre no zoológico.' },
    { jp:'とり', mean:'pássaro', ex:'とりが すきです。', exTr:'Gosto de pássaros.' },
    { jp:'オウム', mean:'papagaio', ex:'オウムが はなします。', exTr:'O papagaio fala.' },
    { jp:'パンダ', mean:'panda', ex:'パンダは かわいいです。', exTr:'O panda é fofo.' }
  ]},
  { id:'b2-objetos', name:'Básico 2 — Objetos e lazer', cards:[
    { jp:'カメラ', mean:'câmera', ex:'あたらしい カメラです。', exTr:'É uma câmera nova.' },
    { jp:'コピー', mean:'cópia', ex:'コピーを とります。', exTr:'Tiro uma cópia.' },
    { jp:'コンピューター', mean:'computador', ex:'コンピューターを つかいます。', exTr:'Uso o computador.' },
    { jp:'きっぷ', mean:'passagem, bilhete', ex:'きっぷを かいます。', exTr:'Compro a passagem.' },
    { jp:'くすり', mean:'remédio', ex:'くすりを のみます。', exTr:'Tomo remédio.' },
    { jp:'しんぶん', mean:'jornal', ex:'あさ しんぶんを よみます。', exTr:'De manhã leio o jornal.' },
    { jp:'てがみ', mean:'carta', ex:'てがみを かきます。', exTr:'Escrevo uma carta.' },
    { jp:'メール', mean:'e-mail', ex:'メールを おくります。', exTr:'Envio um e-mail.' },
    { jp:'ボール', mean:'bola', ex:'ボールで あそびます。', exTr:'Brinco com a bola.' },
    { jp:'ばら', mean:'rosa (flor)', ex:'あかい ばらです。', exTr:'É uma rosa vermelha.' },
    { jp:'は', mean:'dente', ex:'はを みがきます。', exTr:'Escovo os dentes.' },
    { jp:'あめ', mean:'chuva', ex:'きょうは あめです。', exTr:'Hoje está chovendo.' },
    { jp:'アンチーク', mean:'antiguidade', ex:'アンチークが すきです。', exTr:'Gosto de antiguidades.' },
    { jp:'テレビゲーム', mean:'videogame', ex:'テレビゲームを します。', exTr:'Jogo videogame.' },
    { jp:'てんらんかい', mean:'exposição', ex:'てんらんかいへ いきます。', exTr:'Vou à exposição.' },
    { jp:'おんがく', mean:'música', ex:'おんがくを ききます。', exTr:'Ouço música.' },
    { jp:'ゴルフ', mean:'golfe', ex:'ゴルフは たのしいです。', exTr:'Golfe é divertido.' },
    { jp:'ジョギング', mean:'cooper, corrida', ex:'あさ ジョギングを します。', exTr:'De manhã faço cooper.' },
    { jp:'コンサート', mean:'show, concerto', ex:'コンサートへ いきます。', exTr:'Vou ao show.' },
    { jp:'セーター', mean:'suéter', ex:'あたらしい セーターを かいました。', exTr:'Comprei um suéter novo.' },
    { jp:'シャワー', mean:'ducha, chuveiro', ex:'シャワーを あびます。', exTr:'Tomo uma ducha.' },
    { jp:'じこ', mean:'acidente', ex:'じこが ありました。', exTr:'Houve um acidente.' },
    { jp:'ざんぎょう', mean:'hora extra', ex:'きょうは ざんぎょうです。', exTr:'Hoje tem hora extra.' },
    { jp:'そうじ', mean:'faxina, limpeza', ex:'へやの そうじを します。', exTr:'Faço a faxina do quarto.' },
    { jp:'かいもの', mean:'compras', ex:'スーパーで かいものを します。', exTr:'Faço compras no mercado.' },
    { jp:'ちゃいろ', mean:'marrom', ex:'ちゃいろの かばんです。', exTr:'É uma bolsa marrom.' },
    { jp:'ねずみいろ', mean:'cinza', ex:'ねずみいろの くつです。', exTr:'São sapatos cinza.' },
    { jp:'ちゅうごくご', mean:'chinês (idioma)', ex:'ちゅうごくごを べんきょうします。', exTr:'Estudo chinês.' }
  ]},
  { id:'b2-adverbios', name:'Básico 2 — Advérbios e conectivos', cards:[
    { jp:'あまり', mean:'não muito (+ negativo)', ex:'あまり たべません。', exTr:'Não como muito.' },
    { jp:'たくさん', mean:'muito(s), bastante', ex:'ほんが たくさん あります。', exTr:'Há muitos livros.' },
    { jp:'とても', mean:'muito', ex:'とても おいしいです。', exTr:'É muito gostoso.' },
    { jp:'ぜんぜん', mean:'nem um pouco (+ negativo)', ex:'ぜんぜん わかりません。', exTr:'Não entendo nada.' },
    { jp:'ぜんぶで', mean:'ao todo, no total', ex:'ぜんぶで ごひゃくえんです。', exTr:'Ao todo são 500 ienes.' },
    { jp:'いっしょに', mean:'junto', ex:'いっしょに いきましょう。', exTr:'Vamos juntos.' },
    { jp:'ひとりで', mean:'sozinho', ex:'ひとりで たべます。', exTr:'Como sozinho.' },
    { jp:'あるいて', mean:'a pé', ex:'あるいて いきます。', exTr:'Vou a pé.' },
    { jp:'そして', mean:'e, além disso', ex:'やすくて、そして おいしいです。', exTr:'É barato e gostoso.' },
    { jp:'それから', mean:'depois disso, e então', ex:'ごはんを たべました。それから ねました。', exTr:'Comi. Depois disso dormi.' },
    { jp:'それで', mean:'por isso, então', ex:'あめでした。それで いきませんでした。', exTr:'Estava chovendo, por isso não fui.' },
    { jp:'それじゃ', mean:'então, bom (transição)', ex:'それじゃ、また あした。', exTr:'Então, até amanhã.' },
    { jp:'しかし', mean:'mas, porém', ex:'たかいです。しかし いいです。', exTr:'É caro. Mas é bom.' },
    { jp:'～から', mean:'porque, já que', ex:'たかいですから、かいません。', exTr:'Porque é caro, não compro.' },
    { jp:'しか', mean:'apenas, só (+ negativo)', ex:'ひとつしか ありません。', exTr:'Só tenho um.' },
    { jp:'～も', mean:'também', ex:'わたしも いきます。', exTr:'Eu também vou.' }
  ]},
  { id:'b2-expressoes', name:'Básico 2 — Expressões e perguntas', cards:[
    { jp:'どうですか', mean:'que tal?, como está?', ex:'おちゃは どうですか。', exTr:'Que tal um chá?' },
    { jp:'いきましょう', mean:'vamos (ir)', ex:'いっしょに いきましょう。', exTr:'Vamos juntos.' },
    { jp:'いきませんか', mean:'não quer ir?', ex:'えいがに いきませんか。', exTr:'Não quer ir ao cinema?' },
    { jp:'ざんねん', mean:'que pena', ex:'ざんねんですね。', exTr:'Que pena, né.' },
    { jp:'どこにも', mean:'a lugar nenhum (+ negativo)', ex:'どこにも いきません。', exTr:'Não vou a lugar nenhum.' },
    { jp:'どちら', mean:'qual?, onde? (formal)', ex:'おくには どちらですか。', exTr:'De qual país você é?' },
    { jp:'いくら', mean:'quanto (custa)?', ex:'これは いくらですか。', exTr:'Quanto custa isto?' },
    { jp:'いくつ', mean:'quantos?', ex:'いくつ ありますか。', exTr:'Quantos há?' },
    { jp:'なにで', mean:'com o quê?, de que (meio)?', ex:'なにで いきますか。', exTr:'Como (com que meio) você vai?' },
    { jp:'AやB', mean:'A, B, etc. (lista parcial)', ex:'ねこや いぬが すきです。', exTr:'Gosto de gatos, cachorros, etc.' }
  ]}
];
